version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - python
  ignore:
  - dependency-name: fcm-django
    versions:
    - 0.3.7
    - 0.3.8
  - dependency-name: django-extensions
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.1.post1
    - 3.1.2
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
    - 3.1.7
  - dependency-name: djangorestframework
    versions:
    - 3.12.2
  - dependency-name: django-bootstrap4
    versions:
    - 2.3.1
  commit-message:
    prefix: Crowdbotics
